### ISSUE TITLE
Sharing the original SavedModel

### ISSUE THREAD

**Issue by khanhlvg** [reiinakano/arbitrary-image-stylization-tfjs#22]
Hi Nakano-san,

Do you mind sharing the original float SavedModel prior to being converted to TensorFlow.js?

I'm interested in converting the model to TF Lite and use on mobile. It'd be great if I can build on top of your work instead of rebuilding what you have done.

Thanks.

**Comment by reiinakano** [comment]
SavedModels for distilled style and original transformer:
https://drive.google.com/drive/folders/15r48XYPRzBB49PGvnjN9RN3xHogF8u6-?usp=sharing
https://drive.google.com/drive/folders/1-IIg2SotsYlaLJLpI7UTlkCSAZZhxnjD?usp=sharing

The distilled style model here has its variables multiplied by 10 to fix the float16 issue.

Good luck with your project!
