### ISSUE TITLE
Larger images

### ISSUE THREAD

**Issue by PaulBlenkhorn** [reiinakano/arbitrary-image-stylization-tfjs#24]
I've tried to increase the size of the source image (changed index.html) to produce larger stylised images but I can't seem to get beyond 1000x1000.  I get an error: "GL ERROR :GL_OUT_OF_MEMORY : glBufferData: cannot allocate more than 1GB".  Any suggestions?

**Comment by reiinakano** [comment]
Your browser just ran out of memory. It *is* a resource-constrained environment after all. I don't think there's a solution for this other than using another implementation that does not run on the browser. I suggest the original Magenta implementation in Python https://github.com/tensorflow/magenta/tree/master/magenta/models/arbitrary_image_stylization
