### ISSUE TITLE
where is port 9966 configured?

### ISSUE THREAD

**Issue by aspiringguru** [reiinakano/arbitrary-image-stylization-tfjs#27]
I thought I knew yarn/node/javascript.  ¯\_(ツ)_/¯

yarn run start  : checking package.json to see what is executed.

package.json shows 
"scripts": {
    "start": "budo main.js:dist/bundle.js --live --host localhost",

main.js does not contain a reference to port 9966 
directory dist is empty. bundle.js does not exist, yet my localhost is running fine.

Where should I be looking?

**Comment by reiinakano** [comment]
I don't know either, sorry. First place I would look is the budo docs, there might be a cli option to set the port number there.

**Comment by aspiringguru** [comment]
https://github.com/mattdesl/budo/blob/master/docs/command-line-usage.md

https://github.com/mattdesl/budo/blob/master/README.md#cli

edited package.json as below 
    "start": "budo main.js:dist/bundle.js --live --host localhost --port 5000",

thanks. turns out 9966 is a default port # in budo. 

I was looking to rework this into an progressive web app. Javascript is not my power. Any thoughts on how to structure or resources?

also: just found this. the range of in browser options is impressive.

https://bleedingedgepress.com/deep-learning-browser/
https://github.com/backstopmedia/deep-learning-browser
