### ISSUE TITLE
Dimensions of the model

### ISSUE THREAD

**Issue by DavidGOrtega** [reiinakano/arbitrary-image-stylization-tfjs#3]
Hi!

Great work!

I just only wanted to tell you that we just recently ported this model to tfjs from [here](https://github.com/elleryqueenhomels/arbitrary_style_transfer)

We haven't modified the use of the InceptionV3. After the parameters optimisation the total model (we don't expose it as two parts) is just only about 25MB in total and the model is able to run (like yours) if the browser can handle enough RAM creating the WebGL context  (usually limited to 512MB).

So your model is 17MB in total and the model with inceptionV3 is just only 25MB.

Of course that's not the REAL memory consumed by the model on inference.

Again, great work!

**Comment by reiinakano** [comment]
Oh, cool, thanks for letting me know! Maybe I'll try porting the inception
model too.

You should put up a tfjs demo so people can play around with it!
