### ISSUE TITLE
How about migrate the model to the mobile？

### ISSUE THREAD

**Issue by carachan98** [reiinakano/arbitrary-image-stylization-tfjs#6]
Great demo for arbitrary style transfer！
The progress from fixed style images to totally free choices is really exciting. It seems that you are more likely to create a demo with js?  Inspired by this repo, I want to have a try with migrating the model to the mobile like Prisma, just for practice, no commercial use : ).  Since I am not familiar with the tensorflow.js apis, there are few questions:

Is there any way to integrate the .js with android frame? 
Or the possible solution is taking use of the original model (before  combined with js) and trying to reduce it with apis like tensorflow lite?

Looking for your help : )

**Comment by reiinakano** [comment]
Hi! You can check #22. It seems @khanhlvg will work on the same thing.
